### ISSUE TITLE
[TODO] Init the env for test

### ISSUE THREAD

**Issue by Charlie17Li** [Charlie17Li/summer#1]
- [ ] Create 3 clusters with 5 fake-nodes
- [ ] Observe the origin ApiServer with prom
- [ ] Observe the karmada-apiserver with prom
- [ ] Observe the Karmada-AA with prom
- [ ] Observe the memery, cpu with prom
